#%RAML 1.0
title: customer-registration-XPAPI

traits:
  headerCustomer: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/traits/customerHeaderTrait.raml

types:
  requestDataType: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/dataTypes/requestDataType.raml

/customers:
  post:
    description: "This API will register new Customer"

    is:
      - headerCustomer

    body:
      application/json:
        properties:
          customerRegistrationRequest:
            type: requestDataType

        example: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/examples/requestExample.json

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              customerRegistrationResponse:
                type: object
                properties:
                  eventInstanceId:
                    type: string
                    required: true
                    example: "dsfhdbfhsbdfhjsb3784t2wfsd"

                  status:
                    type: string
                    required : true
                    example: "success"

            example: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/examples/responseSuccessExample.json


      400:
        body:
          application/json:
            type: object
            properties:
              customerRegistrationResponse:
                type: object
                properties:
                  eventInstanceId:
                    type: string
                    required: true
                    example: "dsfhdbfhsbdfhjsb3784t2wfsd"

                  status:
                    type: string
                    required : true
                    example: "failure"

            example: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/examples/responseFailureExample.json

