#%RAML 1.0
title: customer-registration-SAPI-GET
description: Retrieve customer specifications

traits:
  headerCustomer: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/traits/customerHeaderTrait.raml

types:
  requestDataType: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/dataTypes/requestDataType.raml

/customers:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            example: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/examples/notificationExample.json
      400:
        body:
          application/json:
            type: object
            example: !include /exchange_modules/49473852-fac9-47f0-9dd5-e373d6b2591d/customer-fragment/1.0.4/examples/notificationFailureExample.json
            
            