#%RAML 1.0 ResourceType

traits:
  headerCustomer: !include /traits/customerHeaderTrait.raml
dataTypes:
  requestDataType: !include /dataTypes/requestDataType.raml
examples:
  notificationExample: !include /examples/notificationExample.json
  notificationSuccessExample: !include /examples/notificationSuccessExample.json
  notificationFailureExample: !include /examples/notificationFailureExample.json
  requestExample: !include /examples/requestExample.json
  responseSuccessExample: !include /examples/responseSuccessExample.json
  responseFailureExample: !include /examples/responseFailureExample.json
  

